server:
  port: 8081
  servlet:
    context-path: /api
spring:
  application:
    name: my-boot
  datasource:
    url: jdbc:postgresql://52.194.25.20:5432/test?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=UTC
    username: ENC(be3N0H9V9zmj6MTzXfHkkA==)
    password: ENC(Aw88PLDWGFS743P2VW17d745EQefmpxR)
    driver-class-name: org.postgresql.Driver
    type: com.alibaba.druid.pool.DruidDataSource
  # 不返回null值
  jackson:
    default-property-inclusion: non_null
# mybatisplus配置
mybatis-plus:
  mapper-locations: classpath:mapper/*Mapper.xml
  configuration:
    # 下划线风格映射到驼峰命名（便于数据库字段映射到java类属性）
    map-underscore-to-camel-case: true
  type-aliases-package: cn.me.myboot.model.po.*
# 日志显示
logging:
  level:
    root: info
    cn.me.myboot.mapper: debug
# jasypt的秘钥
jasypt:
  encryptor:
    #加密秘钥，myBoot md5后base64
    password: M2M4MzhiOTEyNTZhNTFmODQ4NGMwYjllOTBjM2M5ZmM=
    algorithm: PBEWithMD5AndDES
    iv-generator-classname: org.jasypt.iv.NoIvGenerator
